<?php defined('SYSPATH') or die('No direct script access.');
require_once("public/api/facebook/inc/facebook.php");
require_once("public/api/twitter/twitteroauth.php");
return array(
    'favorite_guild_limit'=>'3',
    'favorite_char_limit'=>'3',
    'path' => array(
        'profile' => 'public/uploads/profile/',
        'media' => 'public/uploads/media/',
        'character'=>'public/uploads/character/',
        'guild'=>'public/uploads/guild/',
        'default_image_path'=>'public/uploads/default.jpeg',   
        'advertisement'=>'public/uploads/ad/lotro.jpg', 
        'inline-advertisement'=>'public/uploads/ad/Inline-Ad.jpg', 
        'feed_default_image_path'=>'public/uploads/media/feed_default.jpg',
     ),
    'default_banner' => array(
        '16' => 'birds.png',
        '17' => 'colors.png',
        '18' => 'print.png',
        '19' => 'wood.png',
    ),
       'player_type'=>array(
           '1'=>'PVP',
           '2'=>'PVE',
           '3'=>'RP'
       ),
       'profile_image' =>array(
        'default' =>'default.jpeg',
        '1' =>'profile_image1',
        '2' =>'profile_image2',
        '3' =>'profile_image3'
      ),
       'player_role1'=>'PvP',
       'player_role2'=>'PvE',
       'player_role3'=>'RP',
       'country' =>array(
        "" =>"Select your Country",  
        "AF"=>"Afghanistan",
        "AL"=>"Albania",
        "DZ"=>"Algeria",
        "AS"=>"AMerican SAMoa",
        "AD"=>"Andorra",
        "AO"=>"Angola",
        "AI"=>"Anguilla",
        "AQ"=>"Antarctica",
        "AG"=>"Antigua and Barbuda",
        "AR"=>"Argentina",
        "AM"=>"Armenia",
        "AW"=>"Aruba",
        "AU"=>"Australia",
        "AT"=>"Austria",
        "AZ"=>"Azerbaijan",
        "BS"=>"BahAMas",
        "BH"=>"Bahrain",
        "BD"=>"Bangladesh",
        "BB"=>"Barbados",
        "BY"=>"Belarus",
        "BE"=>"Belgium",
        "BZ"=>"Belize",
        "BJ"=>"Benin",
        "BM"=>"Bermuda",
        "BT"=>"Bhutan",
        "BO"=>"Bolivia",
        "BA"=>"Bosnia and Herzegowina",
        "BW"=>"Botswana",
        "BV"=>"Bouvet Island",
        "BR"=>"Brazil",
        "IO"=>"British Indian Ocean Territory",
        "BN"=>"Brunei DarussalAM",
        "BG"=>"Bulgaria",
        "BF"=>"Burkina Faso",
        "BI"=>"Burundi",
        "KH"=>"CAMbodia",
        "CM"=>"CAMeroon",
        "CA"=>"Canada",
        "CV"=>"Cape Verde",
        "KY"=>"Cayman Islands",
        "CF"=>"Central African Republic",
        "TD"=>"Chad",
        "CL"=>"Chile",
        "CN"=>"China",
        "CX"=>"Christmas Island",
        "CC"=>"Cocos (Keeling) Islands",
        "CO"=>"Colombia",
        "KM"=>"Comoros",
        "CG"=>"Congo",
        "CD"=>"Congo, the Democratic Republic of the",
        "CK"=>"Cook Islands",
        "CR"=>"Costa Rica",
        "CI"=>"Cote d'Ivoire",
        "HR"=>"Croatia (Hrvatska)",
        "CU"=>"Cuba",
        "CY"=>"Cyprus",
        "CZ"=>"Czech Republic",
        "DK"=>"Denmark",
        "DJ"=>"Djibouti",
        "DM"=>"Dominica",
        "DO"=>"Dominican Republic",
        "TP"=>"East Timor",
        "EC"=>"Ecuador",
        "EG"=>"Egypt",
        "SV"=>"El Salvador",
        "GQ"=>"Equatorial Guinea",
        "ER"=>"Eritrea",
        "EE"=>"Estonia",
        "ET"=>"Ethiopia",
        "FK"=>"Falkland Islands (Malvinas)",
        "FO"=>"Faroe Islands",
        "FJ"=>"Fiji",
        "FI"=>"Finland",
        "FR"=>"France",
        "FX"=>"France, Metropolitan",
        "GF"=>"French Guiana",
        "PF"=>"French Polynesia",
        "TF"=>"French Southern Territories",
        "GA"=>"Gabon",
        "GM"=>"GAMbia",
        "GE"=>"Georgia",
        "DE"=>"Germany",
        "GH"=>"Ghana",
        "GI"=>"Gibraltar",
        "GR"=>"Greece",
        "GL"=>"Greenland",
        "GD"=>"Grenada",
        "GP"=>"Guadeloupe",
        "GU"=>"GuAM",
        "GT"=>"Guatemala",
        "GN"=>"Guinea",
        "GW"=>"Guinea-Bissau",
        "GY"=>"Guyana",
        "HT"=>"Haiti",
        "HM"=>"Heard and Mc Donald Islands",
        "VA"=>"Holy See (Vatican City State)",
        "HN"=>"Honduras",
        "HK"=>"Hong Kong",
        "HU"=>"Hungary",
        "IS"=>"Iceland",
        "IN"=>"India",
        "ID"=>"Indonesia",
        "IR"=>"Iran (IslAMic Republic of)",
        "IQ"=>"Iraq",
        "IE"=>"Ireland",
        "IL"=>"Israel",
        "IT"=>"Italy",
        "JM"=>"JAMaica",
        "JP"=>"Japan",
        "JO"=>"Jordan",
        "KZ"=>"Kazakhstan",
        "KE"=>"Kenya",
        "KI"=>"Kiribati",
        "KP"=>"Korea, Democratic People`s Republic of",
        "KR"=>"Korea, Republic of",
        "KW"=>"Kuwait",
        "KG"=>"Kyrgyzstan",
        "LA"=>"Lao People's Democratic Republic",
        "LV"=>"Latvia",
        "LB"=>"Lebanon",
        "LS"=>"Lesotho",
        "LR"=>"Liberia",
        "LY"=>"Libyan Arab JAMahiriya",
        "LI"=>"Liechtenstein",
        "LT"=>"Lithuania",
        "LU"=>"Luxembourg",
        "MO"=>"Macau",
        "MK"=>"Macedonia, The Former Yugoslav Republic of",
        "MG"=>"Madagascar",
        "MW"=>"Malawi",
        "MY"=>"Malaysia",
        "MV"=>"Maldives",
        "ML"=>"Mali",
        "MT"=>"Malta",
        "MH"=>"Marshall Islands",
        "MQ"=>"Martinique",
        "MR"=>"Mauritania",
        "MU"=>"Mauritius",
        "YT"=>"Mayotte",
        "MX"=>"Mexico",
        "FM"=>"Micronesia, Federated States of",
        "MD"=>"Moldova, Republic of",
        "MC"=>"Monaco",
        "MN"=>"Mongolia",
        "MS"=>"Montserrat",
        "MA"=>"Morocco",
        "MZ"=>"MozAMbique",
        "MM"=>"Myanmar",
        "NA"=>"NAMibia",
        "NR"=>"Nauru",
        "NP"=>"Nepal",
        "NL"=>"Netherlands",
        "AN"=>"Netherlands Antilles",
        "NC"=>"New Caledonia",
        "NZ"=>"New Zealand",
        "NI"=>"Nicaragua",
        "NE"=>"Niger",
        "NG"=>"Nigeria",
        "NU"=>"Niue",
        "NF"=>"Norfolk Island",
        "MP"=>"Northern Mariana Islands",
        "NO"=>"Norway",
        "OM"=>"Oman",
        "PK"=>"Pakistan",
        "PW"=>"Palau",
        "PA"=>"PanAMa",
        "PG"=>"Papua New Guinea",
        "PY"=>"Paraguay",
        "PE"=>"Peru",
        "PH"=>"Philippines",
        "PN"=>"Pitcairn",
        "PL"=>"Poland",
        "PT"=>"Portugal",
        "PR"=>"Puerto Rico",
        "QA"=>"Qatar",
        "RE"=>"Reunion",
        "RO"=>"Romania",
        "RU"=>"Russian Federation",
        "RW"=>"Rwanda",
        "KN"=>"Saint Kitts and Nevis",
        "LC"=>"Saint LUCIA",
        "VC"=>"Saint Vincent and the Grenadines",
        "WS"=>"SAMoa",
        "SM"=>"San Marino",
        "ST"=>"Sao Tome and Principe",
        "SA"=>"Saudi Arabia",
        "SN"=>"Senegal",
        "SC"=>"Seychelles",
        "SL"=>"Sierra Leone",
        "SG"=>"Singapore",
        "SK"=>"Slovakia (Slovak Republic)",
        "SI"=>"Slovenia",
        "SB"=>"Solomon Islands",
        "SO"=>"Somalia",
        "ZA"=>"South Africa",
        "GS"=>"South Georgia and the South Sandwich Islands",
        "ES"=>"Spain",
        "LK"=>"Sri Lanka",
        "SH"=>"St. Helena",
        "PM"=>"St. Pierre and Miquelon",
        "SD"=>"Sudan",
        "SR"=>"SurinAMe",
        "SJ"=>"Svalbard and Jan Mayen Islands",
        "SZ"=>"Swaziland",
        "SE"=>"Sweden",
        "CH"=>"Switzerland",
        "SY"=>"Syrian Arab Republic",
        "TW"=>"Taiwan, Province of China",
        "TJ"=>"Tajikistan",
        "TZ"=>"Tanzania, United Republic of",
        "TH"=>"Thailand",
        "TG"=>"Togo",
        "TK"=>"Tokelau",
        "TO"=>"Tonga",
        "TT"=>"Trinidad and Tobago",
        "TN"=>"Tunisia",
        "TR"=>"Turkey",
        "TM"=>"Turkmenistan",
        "TC"=>"Turks and Caicos Islands",
        "TV"=>"Tuvalu",
        "UG"=>"Uganda",
        "UA"=>"Ukraine",
        "AE"=>"United Arab Emirates",
        "GB"=>"United Kingdom",
        "US"=>"United States",
        "UM"=>"United States Minor Outlying Islands",
        "UY"=>"Uruguay",
        "UZ"=>"Uzbekistan",
        "VU"=>"Vanuatu",
        "VE"=>"Venezuela",
        "VN"=>"Viet NAM",
        "VG"=>"Virgin Islands (British)",
        "VI"=>"Virgin Islands (U.S.)",
        "WF"=>"Wallis and Futuna Islands",
        "EH"=>"Western Sahara",
        "YE"=>"Yemen",
        "YU"=>"Yugoslavia",
        "ZM"=>"ZAMbia",
        "ZW"=>"Zimbabwe",
    ),
    'play_style' =>array(
        '1'=>'PvP Only',
        '2'=>'PvE Only',
        '3'=>'Both PvP and PvE Only',
        '4'=>'Both PvP and PvE Only. Learning more to PvP',
        '5'=>'Both PvP and PvE Only. Learning more to PvE',
    ),
     'rsvp_status' =>array(
        '1'=>'No RSVP Necessary',
        '2'=>'All RSVPs Accepted',
        '3'=>'RSVPs Approved Only',
    ),
    'message_sort' =>array(
        ''=>'Sort By...',
        'all'=>'All',
        '0'=>'Unread',
        '1'=>'Read',
    ),
    'rsvp_roles' =>array(
       '1'=>'Tank',
       '2'=>'Healer',
       '3'=>'DPS',
    ),
    'time' =>array(
        '1'=>'12:00AM', '2'=>'12:30AM', '3'=>'1:00AM',  '4'=>'1:30AM',
        '5'=>'2:00AM', '6'=>'2:30AM', '7'=>'3:00AM',  '8'=>'3:30AM',
        '9'=>'4:00AM', '10'=>'4:30AM', '11'=>'5:00AM',  '12'=>'5:30AM',
        '13'=>'6:00AM', '14'=>'6:30AM', '15'=>'7:00AM',  '16'=>'7:30AM',
        '17'=>'8:00AM', '18'=>'8:30AM', '19'=>'9:00AM',  '20'=>'9:30AM',
        '21'=>'10:00AM', '22'=>'10:30AM', '23'=>'11:00AM', '24'=>'11:30AM',
        '25'=>'12:00PM', '26'=>'12:30PM', '27'=>'1:00PM',  '28'=>'1:30PM',
        '29'=>'2:00PM', '30'=>'2:30PM', '31'=>'3:00PM',  '32'=>'3:30PM',
        '33'=>'4:00PM', '34'=>'4:30PM', '35'=>'5:00PM',  '36'=>'5:30PM',
        '37'=>'6:00PM', '38'=>'6:30PM', '39'=>'7:00PM',  '40'=>'7:30PM',
        '41'=>'8:00PM', '42'=>'8:30PM', '43'=>'9:00PM',  '44'=>'9:30PM',
        '45'=>'10:00PM', '46'=>'10:30PM', '47'=>'11:00PM', '48'=>'11:30PM',
    ),
    'facebook' => array(
        'appId' => '286491718168497',
        'appSecret' => '4b8f3f670299261ee1bca4bb1afb65b7',
        'return_url' => URL::site(NULL, 'https').'feeds/',
        'homeurl' => URL::site(NULL, 'https').'feeds/',
        'fbPermissions' => 'publish_stream,user_photos'
    ),
//    // for 127.0.0.1 IP
//    'twitter' => array(
//        'consumer_key' => 'khHJXSrIwgEp3QaG6Z4eQ',
//        'consumer_secret' => 'oKG2ruAJiH8zZpZsha5iIW5Eh73XEtfTTF0KRsgMo',
//        'twitpic_key'=> 'cfda3f075721e6e14059288915bdad87',
//        'oauth_callback' => 'http://127.0.0.1/feeds/twitter_callback'
//    ),
    // for 23.21.174.234 IP
    'twitter' => array(
       'consumer_key' => 'eCkNK3xicdgWcP74wHfVGyTjc',
        'consumer_secret' => 't8p7Bwkg4colFKXcgCYvQZM6dyz1cxpz7jVxy1lxWSKWeQ3uOa',
        'twitpic_key'=> 'cfda3f075721e6e14059288915bdad87',
        'oauth_callback' => URL::site(NULL, 'https').'feeds/twitter_callback'
    ),
    'mail' => array(
        'driver' => 'smtp',
        'hostnAMe' => 'email-smtp.us-east-1.AMazonaws.com',
        'usernAMe' => 'AKIAJBLZ4TZWCCMZ2A7Q',
        'password' => 'AgYnG63y6IisL5f0VDrmEZZgwVfoVw9R92aooFNaQ0ua'
    ),
    
    'single_password' => 'J01NtheZ3rg!',
);
